stack = [5,6,7,8,9]
stack.append("Piyush")
stack.append("Python")
stack.append("AcadView")
print(stack)
print("popped: " + str(stack.pop()))
print(stack)
print("popped: " + str(stack.pop()))
print(stack)
print("popped: " + str(stack.pop()))
print(stack)
print("popped: " + str(stack.pop()))
print(stack)
print("popped: " + str(stack.pop()))
print(stack)
